---
title: Pick your favourite
hero_image: images/banner.png
description: Create a fan website that gives users a choice of content
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6
  completion:
  - internal
- title: Step 7
  completion:
  - external